### ISSUE TITLE
No support on the current Windows photo viewer?

### ISSUE THREAD

**Issue by StefanOltmann** [saschanaz/jxl-winthumb#34] opened 2024-01-27 10:34 UTC
I'm experiencing some confusion with the installation on Windows 11. The application seems to open the old Windows photo viewer, which I wasn't aware still existed.

When I navigate to the destination using the new Windows photo viewer (referred to as "Microsoft Photo"), the JXL doesn't appear. Could it be that Microsoft Photo is no longer utilizing WIC? Is WIC deprecated in this context?

![grafik](https://github.com/saschanaz/jxl-winthumb/assets/9299303/6c7952de-c7b1-4a6f-85ff-6654aa3a000d)

Edit: Dropped the thumbnail question. It required a restart to take off.

**Comment by saschanaz** [comment] 2024-01-27 12:53
Dupe of #21

Yeah, Microsoft dose not care about WIC anymore (see #29) and they use their own undocumented private API to add codec support (used by e.g [HEIF Image Extensions](https://www.microsoft.com/store/productId/9PMMSR1CGPWG?ocid=pdpshare)). I have no idea what the APIs are.

**Closed by saschanaz** 2024-01-27 12:53 UTC
